// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqtN3dye7iVfZk51L3vfX3o_iWGJ9Xec',
    appId: '1:192771545163:web:d70edcc3d57050fa5595ce',
    messagingSenderId: '192771545163',
    projectId: 'new-story-41851',
    authDomain: 'new-story-41851.firebaseapp.com',
    storageBucket: 'new-story-41851.firebasestorage.app',
    measurementId: 'G-F851VDYTG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEI76IAhQ3T4JpHvn6I0I1lGTB8gnvG6w',
    appId: '1:192771545163:android:e93f63565ae9052d5595ce',
    messagingSenderId: '192771545163',
    projectId: 'new-story-41851',
    storageBucket: 'new-story-41851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX3Yg_t3zPGJs3QdhzguUeLk2tefZwjMw',
    appId: '1:192771545163:ios:4e6aa2f43092de145595ce',
    messagingSenderId: '192771545163',
    projectId: 'new-story-41851',
    storageBucket: 'new-story-41851.firebasestorage.app',
    iosBundleId: 'com.example.newStory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX3Yg_t3zPGJs3QdhzguUeLk2tefZwjMw',
    appId: '1:192771545163:ios:4e6aa2f43092de145595ce',
    messagingSenderId: '192771545163',
    projectId: 'new-story-41851',
    storageBucket: 'new-story-41851.firebasestorage.app',
    iosBundleId: 'com.example.newStory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJqtN3dye7iVfZk51L3vfX3o_iWGJ9Xec',
    appId: '1:192771545163:web:43e2adcdeaa0540a5595ce',
    messagingSenderId: '192771545163',
    projectId: 'new-story-41851',
    authDomain: 'new-story-41851.firebaseapp.com',
    storageBucket: 'new-story-41851.firebasestorage.app',
    measurementId: 'G-89ZSPDZF6F',
  );

}